services:
  weblibrary:
    image: weblibrary:0.0.1
    container_name: weblibrary
    build:
      context: .
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "8080:8080"

  postgres_db:
    image: postgres:18.0-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: library
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data:
    name: weblibrary-db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/WebLibraryServer/db-data